var slides = {
  header: 'HYANZA',
  footer: 'MICHALBE',
  slides: [
    "HYANZA",
    "2014",
    "amsterdam",
    "bonjourpack",
    "2015",
    "zanzibar",
    "JELOcartel",
    "apress",
    "MVP",
    "pivot",
    "e-commerce",
    "2016",
    {
      image: "images/glorya.png"
    },
    "(demo?)",
    "2017",
    {
      image: "images/africa.png"
    },
    "+4784",
    "v0.5",
    "what's new",
    "components",
    "smart search",
    "no bower",
    "no jquery",
    "no grunt",
    "new config",
    "themes",
    "index-root",
    "build",
    "l10n",
    "multi-",
    "-kurwa-",
    "-store!",
    "multistore",
    "deps tree",
    "what's missing",
    "images",
    "app state",
    "tests :O",
    "backend++",
    "marketplace",
    "admin",
    "IE support",
    "sass, stylus",
    "php",
    "thanks",
    "Q?",
    "@michalbe"
  ]
};
