var slides = {
  slides: [
    "HYANZA",
    "zanzibar 2014",
    "bonjourpack",
    "2015",
    "JELOcartel",
    "apress",
    "MVP",
    "pivot",
    "e-commerce",
    "2016",
    "glorya",
    "(demo?)",
    "2017",
    "africa",
    "+4784",
    "v0.5",
    "what's new",
    "components",
    "smart search",
    "no bower",
    "no jquery",
    "no grunt",
    "new config",
    "index-root",
    "themes",
    "build",
    "l10n",
    "multi-",
    "-kurwa-",
    "-store!",
    "multistore",
    "deps tree",
    "what's missing",
    "images",
    "global store",
    "tests :O",
    "backend++",
    "marketplace",
    "admin",
    "IE support",
    "sass, stylus",
    "php",
    "thanks",
    "Q?",
    "@michalbe"
  ]
};
